"""Datos de referencia portados del macro VBA (GenerarPL.bas): clasificación por
prefijo de cuenta, traducción ES->EN, alias de clientes y catálogo de orden/labels.

Es la fuente determinista de la lógica (el macro ya cuadra contra la referencia del
cliente). Ver pipelines/pl/ESPECIFICACION.md §3.2, §3.5, §7.
"""

GRUPO_VENTAS_NACIONALES = "4110NS"
LABEL_GMBH_GLOBAL = "  P3 GLOBAL GMBH SERVICES"
LABEL_PTU = "  PTU"

# Prefijo de cuenta -> grupo (espejo de GetGrp en el macro)
RUBRO_POR_GRUPO = {
    "4110": "INCOMES",
    "4210": "OTHER_INCOMES",
    "4310": "OTHER_INCOMES",
    "4510": "OTHER_INCOMES",
    "6001": "EXPENSES",
    "6002": "EXPENSES",
    "6004": "EXPENSES",
    "6005": "EXPENSES",
    "6006": "EXPENSES",
    "6007": "EXPENSES",
    "6008": "EXPENSES",
    "6009": "OTHER_EXPENSES",
    "8000": "ACCRUED_TAXES",
}

# Traducción ES -> EN (función EN del macro; los labels llevan la indentación de la
# referencia). No incluye las cuentas 4110 (ver traducir()).
GLOSARIO_ES_EN = {
    # Other Incomes
    "UTILIDAD CAMBIARIA": "  E.R. FLUCTUATION PROFIT",
    "OTROS INGRESOS": "  OTHER INCOME",
    "INTERESES A FAVOR": "  INTEREST",
    "PRODUCTOS FINANCIEROS": "  FINANCIAL PRODUCTS",
    # 6001 Salaries
    "SUELDOS Y SALARIOS": "  GENERAL DEP",
    "VACACIONES": "  VACATIONS",
    "PRIMA VACACIONAL": "  VACATIONS PREMIUM",
    "AGUINALDO": "  CHRISTMAS BONUS",
    "INDEMNIZACION": "  INDEMNITY",
    "PREMIOS DE ASISTENCIA": "  ASSITANCY BONUS",
    "PREMIOS DE PUNTUALIDAD": "  PUNCTUALITY BONUS",
    "BONO PRODUCTIVIDAD": "  PRODUCTIVITY BONUS",
    "GRATIFICACION ESPECIAL": "  SPECIAL GRATIFICATION",
    "PRIMA DE ANTIGUEDAD": "  SENIORITY PREMIUM",
    # 6002 Social benefits
    "VALES PARA DESPENSA": "  FOOD COUPONS",
    # 6004 Security contributions
    "I.M.S.S.": "  SOCIAL SECURITY CONTRIBUTIONS",
    "R.C.V.": "  INSURANCE RETIR., DISMISS. AND OLD",
    "5% INFONAVIT": "  5% CONTRIB. WORKER'S HOUSING FUND",
    # 6005 Payroll tax
    "IMPUESTOS SOBRE NOMINA": "  PAYROLL TAX",
    # 6006 Fixed expenses
    "TELEFONO": "  TELEPHONE",
    "COMBUSTIBLES Y LUBRICANTES": "  FUEL AND LUBRICANTS",
    "COMISIONES EDENRED": "  COMMISSION ON FOOD COUPONS",
    "ARTICULO DE LIMPIEZA": "  ARTICLE CLEANING",
    "ARTICULOS DE OFICINA Y PAPELERIA": "  STATIONERY",
    "DESPENSA DE OFICINA": "  OFFICE PANTRY",
    "ARRENDAMIENTO DE INMUEBLE PERSONAS MORALES": "  LEASING REAL ESTATE TO INDIVIDUAL",
    "ARRENDAMIENTO DE INMUEBLE PERSONAS FISICAS": "  LEASE OF PROPERTY PF",
    "ARRENDAMIENTO DE EQUIPO COMPUTO": "  LEASING COMPUTER EQUIPMENT",
    "ARRENDAMIENTO DE EQUIPO DE TRANSPORTE": "  LEASING TRANSPORT. EQUIPMENT",
    "DEPRECIACION EQUIPO OFICINA": "  DEPRECIATION OFFICE EQUIPMENT",
    "DEPRECIACION EQUIPO DE COMPUTO": "  DEPRECIATION COMPUTER EQUIPMENT",
    "ACTIVOS MENORES": "  MINOR ASSETS",
    "DEPRECIACION MEJORAS DE EDIFICIOS": "  DEPRECIATION BUILDING IMPROVEMENTS",
    # 6007 Variable expenses
    "MANTENIMIENTO OFICINAS": "  MAINTENANCE OFFICE",
    "SOFTWARE DE COMPUTO": "  COMPUTER SOFTWARE",
    "ESTACIONAMIENTOS": "  PARKING",
    "ESTACIONAMIENTOS VIAJE": "  OTHER TRAVEL EXPENSES",
    "MENSAJERIA": "  COURIER",
    "SEGUROS Y FIANZAS": "  INSURANCE AND BONDS",
    "CUOTAS Y SUSCRIPCIONES": "  FEES AND SUBSCRIPTIONS",
    "UNIFORMES": "  UNIFORMS",
    "NUBE/SOFTWARE": "  CLOUD/SOFTWARE",
    "DOMINIO": "  DOMAIN",
    "SERVICIOS POR ASESORIA": "  ADVISORY SERVICES",
    "HONORARIOS PERSONAS MORALES": "  FEES PAID TO CORPORATIONS",
    "SERVICIOS PROFESIONALES": "  FEES PAID INDIVIDUALS ONE",
    "NO DEDUCIBLES": "  NON-DEDUCTIBLE",
    "HOSPEDAJE": "  LODGING",
    "ALIMENTACION": "  MEALS",
    "TRANSPORTE": "  TRANSPORTATION",
    "USO O GOCE TEMPORAL DE AUTOMOVIL": "  TEMPORARY USE OR ENJOYMENT OF AUTOMOBILE",
    "CASETAS": "  HIGHWAY QUOTAS",
    "BOLETOS DE AVION": "  AIRPLANE TICKETS",
    "GASTOS VIAJE EN GENERAL": "  GENERAL TRAVEL EXPENSES",
    "OTROS GASTOS DE VIAJE": "  OTHER TRAVEL EXPENSES",
    "IMPUESTO SOBRE HOSPEDAJE": "  HOTEL TAX",
    "OTROS GASTOS": "  OTHER EXPENSES",
    "HERRAMIENTAS": "  TOOLS",
    "HARDWARE": "  HARDWARE",
    "SERVICIOS P3 AUTOMOTIVE GMBH": "  P3 AUTOMOTIVE GMBH",
    "P3 GLOBAL GMBH SERVICES": "  P3 GLOBAL GMBH SERVICES",
    "SERVICIOS P3 USA, INC.": "  P3 SERVICES USA",
    "P3 SERVICES DIGITAL GMBH": "  P3 SERVICES DIGITAL",
    # 6008 Financial expenses
    "COMISIONES BANCARIAS": "  BANK COMMISIONS",
    "INTERESES A CARGO": "  INTEREST EXPENSE",
    # 6009 Other expenses
    "PERDIDA CAMBIARIA": "  E.R. FLUCTUATION LOSS",
    # 8000 Taxes
    "I.S.R. DEL EJERCICIO": "  INCOME TAX OF THE YEAR",
    "P.T.U.": "  PTU",
}

# Provisiones de ingreso devengado (cuentas 4110 cuyo nombre empieza en PROVISION):
# nombre-tras-"Provisiones " (upper) -> label ACCRUED REVENUE (rama 4110 de EN).
PROVISIONES_ES_EN = {
    "BMW": "  ACCRUED REVENUE BMW",
    "P3 AUTOMOTIVE": "  ACCRUED REVENUE P3 AUTOMOTIVE",
    "MAGNA SLP": "  ACCRUED REVENUE MAGNA SLP",
    "FORD MOTOR COMPANY S.A. DE C.V.": "  ACCRUED REVENUE FORD",
    "NEW TRANSPORT APPLICATION": "  ACCRUED REVENUE NEW TRANSPORT APPLICATION",
    "P3 USA": "  ACCRUED REVENUE P3 USA",
    "SERVICIOS TURISTICOS EXCLUSIVOS": "  ACCRUED SERVICIOS TURISTICOS EXCLUSIVOS",
    "SCOTIABANK INVERLAT": "  ACCRUED REVENUE SCOTIA BANK",
    "LINDE + WIEMANN": "  ACCRUED REVENUE LINDE + WIEMANN",
    "YANFENG": "  ACCRUED REVENUE YANGFENG",
    "ELANCO": "  ACCRUED REVENUE ELANCO",
    "P3 KOREA": "  ACCRUED REVENUE P3 KOREA",
    "GENTHERM DE MEXICO": "  ACCRUED REVENUE GENTHERM DE MEXICO",
    "FAURECIA": "  ACCRUED REVENUE FAURECIA",
    "AIRBUS": "  ACCRUED REVENUE AIRBUS",
    "DAIKIN": "  ACCRUED REVENUE DAIKIN",
    "VOLKSWAGEN": "  ACCRUED REVENUE VOLKSWAGEN",
    "TEKLAS": "  ACCRUED REVENUE TEKLAS",
    "PLASTIC OMNIUM": "  ACCRUED REVENUE PLASTIC OMNIUM",
    "AUTOELECTRIC": "  ACCRUED REVENUE AUTOELECTRIC",
    "P3 DIGITAL SERVICIO GMBH": "  ACCRUED REVENUE P3 DIGITAL SERVICE GMBH",
}
ACCRUED_REVENUE_OTROS = "  ACCRUED REVENUE OTHERS PROJECTS"

# Alias de clientes de Ventas Nacionales (ENNatSales del macro).
ALIAS_CLIENTES = {
    "AUTOELECTRIC OF AMERICA, INC": "AUTOELECTRIC",
    "AUTOELECTRIC OF AMERICA": "AUTOELECTRIC",
    "VOLKSWAGEN DE MEXICO": "VOLKSWAGEN",
    "VOLKSWAGEN DE MEXICO, S.A. DE C.V.": "VOLKSWAGEN",
    "YANFENG SEATING MEXICO": "OTHER CLIENTS",
    "YANFENG SEATING MEXICO, S.A. DE C.V.": "OTHER CLIENTS",
    "EQUIPO AUTOMOTRIZ AMERICANA": "OTHER CLIENTS",
    "EQUIPO AUTOMOTRIZ AMERICAN": "OTHER CLIENTS",
    "SERVICIOS TURISTICOS EXCLUSIVOS": "SERVICIOS TURISTICOS EXCLUSIVOS, S.A. DE C.V.",
    "SCOTIABANK INVERLAT": "SCOTIA BANK",
    "SCOTIABANK": "SCOTIA BANK",
    "AIRBUS HELICOPTERS MEXICO": "AIRBUS HELICOPTERS MEXICO QUERETARO",
    "AIRBUS HELICOPTERS": "AIRBUS HELICOPTERS MEXICO QUERETARO",
    "SMX SERVICES AND CONSULTING": "SMX SERVICES & CONSULTING",
}

# Catálogo de clientes de Ventas Nacionales (orden de la referencia, InitCatalog 4110NSC).
CATALOGO_NATIONAL_SALES = [
    "FORD MOTOR COMPANY", "BMW SLP", "CF MOTO", "FRAENKISCHE",
    "CONSORCIO INDUSTRIAL MEXICANO DE AUTOPARTES", "KIEKERT DE MEXICO",
    "LEAR CORPORATION", "BORGWARNER", "YANGFENG", "PEASA", "PISA",
    "DRIV DE MEXICO", "DIVERSE", "MOLINA GAULAND & ZEITGEIST", "AUTOELECTRIC",
    "TW DISTRIBUIDORES INDUSTRIALES", "LINDE + WIEMANN", "AKKY ONLINE SOLUTIONS",
    "CONSORCIO CONSULTOR LAR", "QEV TECHNOLOGIES SL", "ELANCO", "ELEKTROKONTAKT",
    "SERVICIOS TURISTICOS EXCLUSIVOS, S.A. DE C.V.", "DHL LAST MILE DELIVERY",
    "NEW TRANSPORT APPLICATIONS", "FEHRER", "TEKLAS", "FAURECIA",
    "INSTITUTO NACIONAL DE CIENCIAS MEDICAS", "DAIKIN", "SAN LUIS METAL FORMING",
    "VOLKSWAGEN", "EQUIPO AUTOMOTRIZ AMERICANA", "AIRBUS HELICOPTERS MEXICO QUERETARO",
    "TB SEWTECH DE MEXICO", "DIGIT AUTOMOTIVE", "SCOTIA BANK", "PLASTIC OMNIUM",
    "PLASTIC TEC", "KNIPPING", "EUROTRANCIATURA DE MEXICO", "BMC DE MEXICO",
    "SMX SERVICES & CONSULTING", "NOMEA GMBH", "P3 KOREA", "OTHER CLIENTS",
]
_NS_CONOCIDOS = set(CATALOGO_NATIONAL_SALES) - {"OTHER CLIENTS"}

# Catálogo de gastos (orden de la referencia, InitCatalog 6001-6008).
CATALOGO_EXPENSES = [
    "  GENERAL DEP", "  VACATIONS", "  VACATIONS PREMIUM", "  CHRISTMAS BONUS",
    "  INDEMNITY", "  ASSITANCY BONUS", "  PUNCTUALITY BONUS", "  PRODUCTIVITY BONUS",
    "  SPECIAL GRATIFICATION", "  SENIORITY PREMIUM",
    "  FOOD COUPONS",
    "  SOCIAL SECURITY CONTRIBUTIONS", "  INSURANCE RETIR., DISMISS. AND OLD",
    "  5% CONTRIB. WORKER'S HOUSING FUND",
    "  PAYROLL TAX",
    "  TELEPHONE", "  FUEL AND LUBRICANTS", "  COMMISSION ON FOOD COUPONS",
    "  ARTICLE CLEANING", "  STATIONERY", "  OFFICE PANTRY",
    "  LEASING REAL ESTATE TO INDIVIDUAL", "  LEASE OF PROPERTY PF",
    "  LEASING COMPUTER EQUIPMENT", "  LEASING TRANSPORT. EQUIPMENT",
    "  DEPRECIATION OFFICE EQUIPMENT", "  DEPRECIATION COMPUTER EQUIPMENT",
    "  MINOR ASSETS", "  DEPRECIATION BUILDING IMPROVEMENTS",
    "  MAINTENANCE OFFICE", "  COMPUTER SOFTWARE", "  PARKING", "  COURIER",
    "  INSURANCE AND BONDS", "  FEES AND SUBSCRIPTIONS", "  UNIFORMS",
    "  CLOUD/SOFTWARE", "  DOMAIN", "  ADVISORY SERVICES",
    "  FEES PAID TO CORPORATIONS", "  FEES PAID INDIVIDUALS ONE", "  NON-DEDUCTIBLE",
    "  LODGING", "  MEALS", "  TRANSPORTATION",
    "  TEMPORARY USE OR ENJOYMENT OF AUTOMOBILE", "  HIGHWAY QUOTAS",
    "  AIRPLANE TICKETS", "  GENERAL TRAVEL EXPENSES", "  OTHER TRAVEL EXPENSES",
    "  HOTEL TAX", "  OTHER EXPENSES", "  TOOLS", "  HARDWARE", "  TRAINING",
    "  P3 AUTOMOTIVE GMBH", "  P3 GLOBAL GMBH SERVICES", "  P3 SERVICES USA",
    "  P3 SERVICES DIGITAL",
    "  BANK COMMISIONS", "  INTEREST EXPENSE",
    "  PTU",
]

CATALOGO_ACCRUED_REVENUE = [
    "  ACCRUED REVENUE P3 USA", "  ACCRUED REVENUE P3 AUTOMOTIVE",
    "  ACCRUED REVENUE P3 KOREA", "  ACCRUED REVENUE FORD",
    "  ACCRUED REVENUE MAGNA SLP", "  ACCRUED REVENUE P3 DIGITAL SERVICE GMBH",
    "  ACCRUED REVENUE BMW", "  ACCRUED REVENUE LEAR", "  ACCRUED REVENUE TEKLAS",
    "  ACCRUED REVENUE NEW TRANSPORT APPLICATION", "  ACCRUED REVENUE YANGFENG",
    "  ACCRUED INSTITUTO NACIONAL DE SCIENCIAS MEDICAS",
    "  ACCRUED SERVICIOS TURISTICOS EXCLUSIVOS", "  ACCRUED REVENUE AIRBUS",
    "  ACCRUED REVENUE DAIKIN", "  ACCRUED REVENUE VOLKSWAGEN",
    "  ACCRUED REVENUE AUTOELECTRIC", "  ACCRUED REVENUE CIENCIAS MEDICAS",
    "  ACCRUED REVENUE ELANCO", "  ACCRUED REVENUE LINDE + WIEMANN",
    "  ACCRUED REVENUE FRAENKISCHE", "  ACCRUED REVENUE SCOTIA BANK",
    "  ACCRUED REVENUE PLASTIC OMNIUM", "  ACCRUED REVENUE FAURECIA",
    "  ACCRUED REVENUE GENTHERM DE MEXICO", ACCRUED_REVENUE_OTROS,
]

CATALOGO_OTHER_INCOMES = [
    "  E.R. FLUCTUATION PROFIT", "  OTHER INCOME", "  INTEREST", "  FINANCIAL PRODUCTS",
]
CATALOGO_OTHER_EXPENSES = ["  E.R. FLUCTUATION LOSS"]
CATALOGO_ACCRUED_TAXES = ["  INCOME TAX OF THE YEAR"]


def grupo_por_numero(numero_cuenta: str) -> str:
    """Devuelve el grupo del macro a partir del número de cuenta, o '' si no aplica."""
    c = numero_cuenta.strip()
    if c[:4] in ("4110", "4210", "4310", "4510"):
        return c[:4]
    for sufijo, grupo in (
        ("6100-001", "6001"),
        ("6100-002", "6002"),
        ("6100-004", "6004"),
        ("6100-005", "6005"),
        ("6100-006", "6006"),
        ("6100-007", "6007"),
        ("6100-008", "6008"),
        ("6100-009", "6009"),
    ):
        if c[:8] == sufijo:
            return grupo
    if c[:11] == "0000-000-80" or c[:4] == "8000":
        return "8000"
    return ""


def clasificar_por_numero(numero_cuenta: str) -> tuple[str, str]:
    """(grupo, rubro) deterministas de referencia. rubro == '' si la cuenta se ignora."""
    grupo = grupo_por_numero(numero_cuenta)
    return grupo, RUBRO_POR_GRUPO.get(grupo, "")


def traducir(nombre_es: str, grupo: str = "") -> str:
    """Traducción ES->EN (función EN del macro). Las provisiones 4110 se mapean a
    su label ACCRUED REVENUE; si no hay match, devuelve el nombre indentado."""
    n = nombre_es.strip().upper()
    if grupo == "4110":
        if n == "VENTAS NACIONALES":
            return "NATIONAL SALES"
        if n.startswith("PROVISIONE"):
            cliente = nombre_es.strip()[len("Provisiones "):].strip().upper()
            return PROVISIONES_ES_EN.get(cliente, ACCRUED_REVENUE_OTROS)
        return nombre_es.strip()
    if "CAPACITACI" in n:
        return "  TRAINING"
    return GLOSARIO_ES_EN.get(n, "  " + nombre_es.strip())


def normalizar_cliente(raw: str) -> str:
    """Razón social cruda -> cliente canónico del catálogo; desconocidos -> OTHER CLIENTS
    (reproduce ENNatSales + el bucketing de LookupAmt en el macro)."""
    n = raw.strip().upper()
    canonico = ALIAS_CLIENTES.get(n, n)
    return canonico if canonico in _NS_CONOCIDOS else "OTHER CLIENTS"
